#Anything that is optional which you are not using, just delete that line. You can also delete any of the '#comments'
 
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="All rights reserved" #mandatory https://choosealicense.com/
issueTrackerURL="http://my.issue.tracker/" #optional
 
[[mods]] #mandatory
modId="gardenmod" #mandatory
version="0.0.1" #mandatory
displayName="Vital1ks' Garden Mod" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/forgiveness#c13" #optional
logoFile="logo.png" #optional
credits='''
                            
Thanks for ideas:                  
- paximouse                        
                                   
Special thanks:                  
- heybosoc                      
''' #optional
authors="Vital1kS" #optional
description='''
This mod will allow you to craft some things
but in difficult recipes you will lose
some of the things that this item consisted of.
''' #mandatory
